project:
  type: website
  output-dir: _site
website:
  title: OEO Report Dashboard
  navbar:
    search: true
    left:
    - href: index.qmd
      text: Home
    - text: Reports
      menu:
      - text: utopia
        href: reports/utopia/index.qmd
      - text: US_9R_8D
        href: reports/US_9R_8D/index.qmd
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-links:
      - repo: https://github.com/ParticularlyPythonicBS/oeo-reports
        icon: github
        text: View on GitHub
        href: https://github.com/ParticularlyPythonicBS/oeo-reports

execute:
  cache: true
