project:
  type: website
  output-dir: docs
website:
  title: OEO Report Dashboard
  navbar:
    search: true
    left:
    - href: index.qmd
      text: Home
    - text: Reports
      menu:
      - text: utopia
        href: reports/utopia/index.qmd
      - text: US_9R_8D
        href: reports/US_9R_8D/index.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
